apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: gcp-logging-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag kubernetes.*
      format json
    </source>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        container_name ${record["kubernetes"]["container_name"] rescue "unknown"}
        namespace_name ${record["kubernetes"]["namespace_name"] rescue "unknown"}
        pod_name ${record["kubernetes"]["pod_name"] rescue "unknown"}
      </record>
    </filter>

    <match kubernetes.**>
      @type google_cloud
      detect_json true
      use_metadata_service false

      <auth>
        json_key /var/secrets/google/key.json
      </auth>

      <metadata>
        project_id suncoast-systems-infra-0e1b
        location us-east1
        cluster_name suncoast-systems-k8s-cluster
        namespace_id ${record["kubernetes"]["namespace_name"]}
        pod_id ${record["kubernetes"]["pod_name"]}
        container_name ${record["kubernetes"]["container_name"]}
      </metadata>

      <buffer>
        flush_mode interval
        retry_type exponential_backoff
        @type memory
        flush_interval 5s
        retry_max_times 5
        chunk_limit_size 2M
        queue_limit_length 8
      </buffer>
    </match>


