apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: gcp-logging-system
data:
  fluent.conf: |
    <source>
      @type tail
      path "/var/log/containers/*.log"
      pos_file "/fluentd/log/containers.log.pos"
      tag "kubernetes.*"
      read_from_head true
      <parse>
        @type none
      </parse>
    </source>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        log ${record["log"] || record["message"] || record.to_s}
        severity ${record["severity"] || "INFO"}
      </record>
    </filter>

    <match kubernetes.**>
      @type google_cloud
      detect_json false
      use_metadata_service false
      <buffer>
        flush_mode interval
        flush_interval 5s
        retry_type exponential_backoff
        retry_max_times 5
        chunk_limit_size 2M
        queue_limit_length 8
      </buffer>
    </match>


