apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-custom-parsers
  namespace: fluentd
  labels:
    app.kubernetes.io/name: fluentd
data:
  custom-parsers.conf: |
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field false
      <parse>
        @type json
        time_key ts
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </filter>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: gcp-logging-system
data:
  fluent.conf: |
    @include /fluentd/etc/custom-parsers.conf

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        keep_time_key true
      </parse>
    </source>

    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field false
      <parse>
        @type json
        time_key ts
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </filter>

    <match kubernetes.**>
      @type google_cloud
      detect_json true
      use_metadata_service false

      <auth>
        json_key /var/secrets/google/key.json
      </auth>

      <buffer>
        flush_mode interval
        retry_type exponential_backoff
        @type memory
        flush_interval 5s
        retry_max_times 5
        chunk_limit_size 2M
        queue_limit_length 8
      </buffer>
    </match>


