apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: gcp-logging-system
data:
  fluent.conf: |
    <source>
      @type dummy
      tag test.gcp
      dummy {"log":"Hello from Fluentd!"}
    </source>

    <match test.gcp>
      @type google_cloud
      project_id suncoast-systems-infra-0e1b
      detect_json false
      use_metadata_service false

      <buffer>
        flush_interval 5s
      </buffer>
    </match>

    <system>
      log_level debug
    </system>
